# Pre-commit hooks configuration
# Install with: uv pip install pre-commit && pre-commit install

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: []

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  # Pytest - Run tests before commit (optional, can be slow)
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'uv run pytest tests/ -v'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
